/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Entity.Candidat;
import Entity.Liceu;
import Singleton.Singleton;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ynad
 */
public class RaportView extends javax.swing.JPanel {
    
    Document d;
    public RaportView() throws FileNotFoundException, DocumentException {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        JudetCB1 = new javax.swing.JComboBox();
        JudetCB2 = new javax.swing.JComboBox();
        LiceeCB = new javax.swing.JComboBox();
        TaraCheckBox = new javax.swing.JCheckBox();
        JudetCheckBox = new javax.swing.JCheckBox();
        LiceuCheckBox = new javax.swing.JCheckBox();
        GenerateRaport = new javax.swing.JButton();

        TitleLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 0, 255));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Generare raport");

        JudetCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudetCB2ActionPerformed(evt);
            }
        });

        TaraCheckBox.setText("Situatia pe tara");

        JudetCheckBox.setText("Situatia pe judet");
        JudetCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudetCheckBoxActionPerformed(evt);
            }
        });

        LiceuCheckBox.setText("Situatia pe liceu");
        LiceuCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiceuCheckBoxActionPerformed(evt);
            }
        });

        GenerateRaport.setText("Raport");
        GenerateRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateRaportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TaraCheckBox)
                            .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JudetCheckBox)
                                    .addComponent(LiceuCheckBox))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JudetCB2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JudetCB1, 0, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LiceeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(GenerateRaport, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaraCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JudetCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JudetCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LiceeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LiceuCheckBox)
                    .addComponent(JudetCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(GenerateRaport)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JudetCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudetCheckBoxActionPerformed
        if(JudetCheckBox.isSelected()){
            JudetCB1.setModel(new DefaultComboBoxModel(Singleton.getInstance().Counties.toArray()));
        }else{
            JudetCB1.setModel(new DefaultComboBoxModel());
        }
    }//GEN-LAST:event_JudetCheckBoxActionPerformed

    private void LiceuCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiceuCheckBoxActionPerformed
        if(LiceuCheckBox.isSelected()){
            JudetCB2.setModel(new DefaultComboBoxModel(Singleton.getInstance().Counties.toArray()));
        }else{
            JudetCB2.setModel(new DefaultComboBoxModel());
        }
    }//GEN-LAST:event_LiceuCheckBoxActionPerformed

    private void JudetCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudetCB2ActionPerformed
         if(JudetCB2.getSelectedItem() != null){
            LiceeCB.setModel(new DefaultComboBoxModel(Liceu.getLiceeJudet(JudetCB2.getSelectedItem().toString()).toArray()));
            LiceeCB.setSelectedItem(null);
        }
    }//GEN-LAST:event_JudetCB2ActionPerformed

    private void GenerateRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateRaportActionPerformed
        try {
            generateRaport();
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(RaportView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GenerateRaportActionPerformed

    public void init() throws FileNotFoundException, DocumentException{
        
        

    }
    
    public float generateTaraRaport(){
        
        float count = Singleton.getInstance().Candidati.size();
        float promovati = 0;
        for(Candidat x:Singleton.getInstance().Candidati){
            if(x.getMedie() >= 6){
                promovati++;
            }
        }
        return (promovati/count)*100;
    }
    
    public float generateJudetRaport(){
        float count = Candidat.getCandidatiJudet(JudetCB1.getSelectedItem().toString()).size();
        float promovati = 0;
        for(Candidat x:Candidat.getCandidatiJudet(JudetCB1.getSelectedItem().toString())){
            if(x.getMedie() >= 6){
                promovati++;
            }
        }
        return (promovati/count)*100;
    }
    
    public float generateLiceuRaport(){
        float count = Candidat.getCandidatiJudet(JudetCB2.getSelectedItem().toString()).size();
        float promovati = 0;
        for(Candidat x:Candidat.getCandidatiJudet(JudetCB2.getSelectedItem().toString())){
            if(x.getLiceu().getNume().equals(LiceeCB.getSelectedItem().toString()) && x.getMedie() >= 6){
                promovati++;
            }
        }
        return (promovati/count)*100;
    }
    
    private void writeCountryReport() throws DocumentException{
        d.add(new Paragraph("Raport pe tara.Promovabilitate: "+generateTaraRaport()+"%"));
    }
    private void writeCountyReport() throws DocumentException{
        d.add(new Paragraph("Raport pe judetul "+JudetCB1.getSelectedItem().toString()+".Promovabilitate: "+generateJudetRaport()+"%"));
    }
    private void writeHighSchoolReport() throws DocumentException{
        d.add(new Paragraph("Raport pe Liceul "+LiceeCB.getSelectedItem().toString()+" din judetul "
                + JudetCB2.getSelectedItem().toString()+".Promovabilitate :"+generateLiceuRaport()+"%"));
    }

    public void generateRaport() throws FileNotFoundException, DocumentException{
        
        d = new Document();
        PdfWriter.getInstance(d, new FileOutputStream("Raport.pdf"));
        d.open();
        d.addTitle("Raport situatie bac anul "+String.valueOf(Calendar.getInstance().get(Calendar.YEAR)));
        if(TaraCheckBox.isSelected()){
            writeCountryReport();
        }
        if(JudetCheckBox.isSelected()){
            writeCountyReport();
        }
        if(LiceuCheckBox.isSelected() && ableToPressRaport()){
            writeHighSchoolReport();
        }
        
        JOptionPane.showMessageDialog(this, "Raport creat!");
        d.close();
        
    }
    
    public boolean ableToPressRaport(){
            if(JudetCB2.getSelectedIndex() != -1){
                if(LiceeCB.getSelectedIndex() != -1){
                    return true;
                }
            }
        
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateRaport;
    private javax.swing.JComboBox JudetCB1;
    private javax.swing.JComboBox JudetCB2;
    private javax.swing.JCheckBox JudetCheckBox;
    private javax.swing.JComboBox LiceeCB;
    private javax.swing.JCheckBox LiceuCheckBox;
    private javax.swing.JCheckBox TaraCheckBox;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
